[template]
src   = "id_rsa.encrypted.tmpl"
dest  = "/root/.ssh/id_rsa.encrypted"
uid = 0
gid = 0
mode  = "0600"
keys = [
  "image-factory"
]
reload_cmd = "/bin/bash -c '/usr/local/bin/decrypt-ssh-keys.sh 2>&1 | logger -p local0.info -t \"id_rsa_reload[$$]\"'"